# -*- coding: utf-8 -*-
"""genElaData

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15sd2mW0iqduS8sq163Dn5JPCLTsuL2da
"""

import random
import json

li = [1,2,3,4,5]

nText = 15
filename = 'data.json'

for i in range(nText):
    random.shuffle(li)
    surrText = ""
    count = 5
    for ele in li:
        instanceText = "RO"+str(ele)
        instanceText += (" "+instanceText)*(count-1)
        if len(surrText) == 0:
            surrText = instanceText
        else:
            surrText += (" "+instanceText)
        count -= 1
    #print(surrText)
    data1 = {"index":{"_id":i+1}}

    data2 = {
      "text": surrText,
      "image": "ImagePath",
    }

    with open(filename,'a') as f: 
        json.dump(data1, f)
        f.write('\n')
        json.dump(data2, f)
        f.write('\n')
    '''jsonData1 = json.dumps(data1)
    jsonData2 = json.dumps(data2)

    print(jsonData1,jsonData2)'''